name: Test

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      selenoid:
        image: aerokube/selenoid:latest
        ports:
          - 4444:4444
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
        env:
          OVERRIDE_HOME: /home/selenoid
        options: >-
          --health-cmd "curl -f http://localhost:4444/status || exit 1"
          --health-interval 5s
          --health-timeout 10s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Make gradlew executable
        run: chmod +x gradlew

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Verify Selenoid is ready
        run: |
          echo "Checking Selenoid status..."
          curl -s http://localhost:4444/status | jq -r '.value.ready' | grep 'true' || exit 1
          echo "Selenoid is ready!"

      - name: Run tests
        run: ./gradlew clean test -Dselenide.remote=http://localhost:4444/wd/hub

      - name: Prepare Allure results
        if: always()
        run: |
          mkdir -p allure-results
          [ -d build/allure-results ] && cp -r build/allure-results/* allure-results/

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-results
          path: allure-results
          retention-days: 5