name: Test

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      selenoid:
        image: aerokube/selenoid:1.10.7  # Фиксированная стабильная версия
        ports:
          - 4444:4444
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - ./browsers.json:/etc/selenoid/browsers.json:ro
        options: >-
          --health-cmd "curl -f http://localhost:4444/status || exit 1"
          --health-interval 10s
          --health-timeout 30s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - run: chmod +x gradlew

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Prepare browsers.json
        run: |
          echo '{
            "chrome": {
              "default": "125.0",
              "versions": {
                "125.0": {
                  "image": "selenoid/chrome:125.0",
                  "port": "4444",
                  "path": "/",
                  "env": ["TZ=UTC"],
                  "volumes": ["/tmp:/tmp"],
                  "tmpfs": {"/tmp": "size=512m"}
                }
              }
            }
          }' > browsers.json
          
          docker pull selenoid/chrome:125.0

      - name: Wait for Selenoid
        run: |
          for i in {1..15}; do
            if curl -s http://localhost:4444/status | grep -q '"total":'; then
              echo "Selenoid ready!"
              curl http://localhost:4444/status
              break
            fi
            sleep 3
          done

      - name: Debug Selenoid
        if: failure()
        run: |
          docker ps -a
          docker logs selenoid
          curl -v http://localhost:4444/status

      - name: Run tests
        run: |
          ./gradlew clean test \
            -Dselenide.remote=http://localhost:4444/wd/hub \
            -Dselenide.browser=chrome \
            -Dselenide.browserVersion=125.0 \
            -Dremote.timeout=90000

      - uses: simple-elf/allure-report-action@master
        if: always()
        with:
          gh_pages: gh-pages
          allure_results: build/allure-results
          allure_report: allure-report
          allure_history: allure-history
            # публикуем отчет
      - uses: peaceiris/actions-gh-pages@v2
        if: always()
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history