name: Test

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      selenoid:
        image: aerokube/selenoid:latest
        ports:
          - 4444:4444
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
        options: >-
          --health-cmd "curl -f http://localhost:4444/status || exit 1"
          --health-interval 5s
          --health-timeout 10s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - run: chmod +x gradlew

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Prepare browsers.json
        run: |
          mkdir -p ~/.aerokube/selenoid
          echo '{
            "chrome": {
              "default": "latest",
              "versions": {
                "latest": {
                  "image": "selenoid/chrome:latest",
                  "port": "4444",
                  "path": "/"
                }
              }
            }
          }' > ~/.aerokube/selenoid/browsers.json

      - name: Wait for Selenoid
        run: |
          for i in {1..10}; do
            if curl -s http://localhost:4444/status | grep -q '"total":'; then
              echo "Selenoid ready!"
              break
            fi
            echo "Waiting for Selenoid..."
            sleep 3
          done

      - run: ./gradlew clean test -Dselenide.remote=http://localhost:4444/wd/hub

      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: logs
          path: |
            build/reports/tests/test
            build/allure-results