name: Test

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      selenoid:
        image: aerokube/selenoid:2.0.1
        ports:
          - 4444:4444
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - ./browsers.json:/etc/selenoid/browsers.json:ro
        options: >-
          --health-cmd "curl -f http://localhost:4444/status || exit 1"
          --health-interval 5s
          --health-timeout 10s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - run: chmod +x gradlew

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Prepare Selenoid config
        run: |
          echo '{
            "chrome": {
              "default": "125.0",
              "versions": {
                "125.0": {
                  "image": "selenoid/chrome:125.0",
                  "port": "4444",
                  "path": "/",
                  "env": ["TZ=UTC"],
                  "volumes": ["/tmp:/tmp"],
                  "tmpfs": {"/tmp": "size=512m"}
                }
              }
            }
          }' > browsers.json
          
          docker pull selenoid/chrome:125.0

      - name: Wait for Selenoid
        run: |
          for i in {1..15}; do
            if curl -s http://localhost:4444/status | grep -q '"total":'; then
              echo "Selenoid ready!"
              curl http://localhost:4444/status
              break
            fi
            echo "Waiting for Selenoid (attempt $i)..."
            sleep 3
          done

      - name: Run tests with Selenoid
        run: |
          ./gradlew clean test \
            -Dselenide.remote=http://localhost:4444/wd/hub \
            -Dselenide.browser=chrome \
            -Dselenide.browserVersion=125.0 \
            -Dremote.timeout=90000 \
            -Dwebdriver.chrome.whitelistedIps=""

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: |
            build/reports/tests/test
            build/allure-results
            browsers.json

      - uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Setup Allure reporting
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          gh_pages: gh-pages
          allure_results: build/allure-results
          allure_report: allure-report

      - name: Deploy report
        uses: peaceiris/actions-gh-pages@v4
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./allure-report
          force_orphan: true