name: Test

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      selenoid:
        image: aerokube/selenoid:latest
        ports:
          - 4444:4444
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - ./browsers.json:/etc/selenoid/browsers.json:ro
        options: >-
          --health-cmd "curl -f http://localhost:4444/status || exit 1"
          --health-interval 5s
          --health-timeout 10s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - run: chmod +x gradlew

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Prepare Selenoid config
        run: |
          echo '{
            "chrome": {
              "default": "125.0",
              "versions": {
                "125.0": {
                  "image": "selenoid/chrome:125.0",
                  "port": "4444",
                  "path": "/",
                  "env": ["TZ=UTC"]
                }
              }
            }
          }' > browsers.json

      - name: Pull browser image
        run: docker pull selenoid/chrome:125.0

      - name: Wait for Selenoid
        run: |
          for i in {1..15}; do
            if curl -s http://localhost:4444/status | grep -q '"total":'; then
              echo "Selenoid ready!"
              curl http://localhost:4444/status
              break
            fi
            echo "Waiting for Selenoid (attempt $i)..."
            sleep 3
          done

      - name: Run tests
        run: |
          ./gradlew clean test \
            -Dselenide.remote=http://localhost:4444/wd/hub \
            -Dselenide.browser=chrome \
            -Dremote.timeout=90000 \
            -Dwebdriver.chrome.driver=/usr/bin/chromedriver

      - name: Collect logs
        if: always()
        run: |
          docker logs selenoid > selenoid.log
          docker ps -a > containers.log
        continue-on-error: true

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: diagnostics
          path: |
            selenoid.log
            containers.log
            build/reports/tests/test/*