name: Test

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: chmod +x gradlew

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # Явно скачиваем образ браузера
      - name: Pull browser image
        run: docker pull selenoid/chrome:latest

      # Запускаем Selenoid с явной конфигурацией
      - name: Start Selenoid
        run: |
          mkdir -p ~/.aerokube/selenoid
          echo '{
            "chrome": {
              "default": "latest",
              "versions": {
                "latest": {
                  "image": "selenoid/chrome:latest",
                  "port": "4444",
                  "path": "/"
                }
              }
            }
          }' > ~/.aerokube/selenoid/browsers.json
          
          docker run -d --name selenoid \
            -p 4444:4444 \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v ~/.aerokube/selenoid:/etc/selenoid \
            aerokube/selenoid:latest

      # Ждём готовности Selenoid
      - name: Wait for Selenoid
        run: |
          for i in {1..10}; do
            if curl -s http://localhost:4444/status | grep -q '"total":'; then
              echo "Selenoid ready!"
              break
            fi
            echo "Waiting for Selenoid (attempt $i)..."
            sleep 3
          done

      # Запускаем тесты с debug-логами
      - run: ./gradlew clean test -Dselenide.remote=http://localhost:4444/wd/hub -Dselenide.browser=chrome -Dremote.timeout=60000

      # Сохраняем логи при ошибке
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: selenoid-logs
          path: |
            /home/runner/.aerokube/selenoid/logs/*